name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push en main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Definir la variable de entorno
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL_PROD }}" >> $GITHUB_ENV

      - name: Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: Construir el proyecto
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: yarn vite build

      - name: Subir solo el contenido de dist a la rama produccion
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Cambiar a la rama produccion o crearla si no existe
          git checkout --orphan produccion || git checkout produccion
          git reset --hard

          # Mover el contenido de dist a la raÃ­z
          mv dist/* .

          # Eliminar la carpeta dist vacÃ­a y cualquier otro archivo innecesario
          rm -rf dist node_modules

          # Agregar solo los archivos movidos
          git add .

          # Confirmar los cambios
          git commit -m "ðŸš€ Build automÃ¡tico desde main"

          # Forzar el push a la rama produccion
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin produccion --force
