name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push en main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: Construir el proyecto
        run: yarn vite build

      - name: Subir archivos a la rama produccion
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan produccion
          git reset --hard
          git add -f dist
          git commit -m "ðŸš€ Build automÃ¡tico desde main"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git produccion --force
